### ISSUE TITLE
Error upgrade scrapy 1.6

### ISSUE THREAD

**Issue by alejandrohdo** [jschnurr/scrapyscript#7]
I upgraded scrapy to 1.6, and I get this error, it is possible that we can make an improvement ?, I do not know if it can generate an error when running my spiders

`ERROR: scrapyscript 1.0.0 has requirement Scrapy==1.4.0, but you'll have scrapy 1.6.0 which is incompatible.`

Thanks!

**Comment by jschnurr** [comment]
v1.1.0 supports the latest version of Scrapy.
