### ISSUE TITLE
it is printing all log

### ISSUE THREAD

**Issue by chiragkanhasoft** [jschnurr/scrapyscript#8]
i have enabled only error log to print using below command
celery -A scraper_api worker -l error

when i run scraping as celery task and i have enable only error log and in scrapy setting i have disabled log still it is printing all logs.

![image](https://user-images.githubusercontent.com/27885527/76852075-9b56bc00-6870-11ea-9238-0b029a33890b.png)

**Comment by jschnurr** [comment]
Try adjusting the setting and passing it to the `Processor()` constructor.

```python
settings = scrapy.settings.Settings(values={'LOG_LEVEL': 'WARNING'})
processor = Processor(settings=settings)
```
